baseurl = "/"
languageCode = "en-us"
title = "R-Ladies Sydney"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Events"
    url = "/events/"
    weight = 3
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 4

[params]
    description = "R-Ladies Sydney"
    footer = '&copy; [R-Ladies Sydney](https://rladiessydney.org) 2018 | <a href="http://meetup.com/rladies-sydney" title="Meetup" style="text-decoration:none"><i class="fa fa-meetup"></i></a>&nbsp;<a href="https://twitter.com/RLadiesSydney" title="Twitter" style="text-decoration:none"><i class="fa fa-twitter"></i></a>&nbsp;<a href="https://github.com/rladiessydney" title="GitHub" style="text-decoration:none"><i class="fa fa-github"></i></a></span>'
